### ISSUE TITLE
What service do I have to use in RIOT to use this?

### ISSUE THREAD

**Issue by Citrullin** [HendrikVE/RiotBleShellApp#1]

**Comment by HendrikVE** [comment]
I have an open PR at the RIOT repository. You can find it over here: https://github.com/RIOT-OS/RIOT/pull/12012

**Comment by HendrikVE** [comment]
Be aware of the little required change you have to do right now in nimble, as described in the PR ;)

**Comment by Citrullin** [comment]
@HendrikVE Thanks. I will take a look into it. :)
